# Generated by Django 5.2.4 on 2025-07-14 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisan_crm.leadstage'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_tags',
            field=models.ManyToManyField(blank=True, to='artisan_crm.tag'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_crm.customerprofile'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_crm.tag'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='artisan_crm.customerprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artisan_crm.customerprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan_crm.leadstage'),
        ),
    ]
